### ISSUE TITLE
Unable to modify the default Player Webpage

### ISSUE THREAD

**Issue by SavageCoder09** [EpicGamesExt/PixelStreamingInfrastructure#681]
## Component your question relates to
- [ O] Frontend library
- [ O] Frontend UI library

## Background
I am customing the default pixel streamig player webpage to exclude the full screen icon, info icon, settings icon, and wifi icon.
My customized code used to work in UE5.4- UE5.6. But lately every time I build the player webpage, it says Cannot find name 'UIElementCreationMode'. 

This is the code that was working until recently:

`Copyright Epic Games, Inc. All Rights Reserved.

export * from '@epicgames-ps/lib-pixelstreamingfrontend-ue5.6';
export * from '@epicgames-ps/lib-pixelstreamingfrontend-ui-ue5.6';
import { Config, PixelStreaming, Logger, LogLevel } from '@epicgames-ps/lib-pixelstreamingfrontend-ue5.6';
import { Application, PixelStreamingApplicationStyle, UIElementCreationMode } from '@epicgames-ps/lib-pixelstreamingfrontend-ui-ue5.6';
const PixelStreamingApplicationStyles =
    new PixelStreamingApplicationStyle();
PixelStreamingApplicationStyles.applyStyleSheet();

// expose the pixel streaming object for hooking into. tests etc.
declare global {
    interface Window { pixelStreaming: PixelStreaming; }
}

document.body.onload = function() {
    Logger.InitLogging(LogLevel.Warning, true);

	// Create a config object
	const config = new Config({ useUrlParams: true });

	// Create the main Pixel Streaming object for interfacing with the web-API of Pixel Streaming
	const stream = new PixelStreaming(config);

	const application = new Application({
		stream,
		onColorModeChanged: (isLightMode) => PixelStreamingApplicationStyles.setColorMode(isLightMode),
		settingsPanelConfig: { 
			isEnabled : false,
			visibilityButtonConfig : { creationMode : UIElementCreationMode.Disable }
		},
		// ❌ Hide Stats button
		statsPanelConfig: {
			isEnabled: false,
			visibilityButtonConfig: { creationMode: UIElementCreationMode.Disable }
		},
	
		// ❌ Hide Fullscreen button
		fullScreenControlsConfig: {
			creationMode: UIElementCreationMode.Disable
		},
	
		// ❌ Hide QP indicator (WiFi icon)
		videoQpIndicatorConfig: {
			disableIndicator: true
		}

	});

document.body.appendChild(application.rootElement);

window.pixelStreaming = stream;}`

This is the documentation I had been referring to till date:
https://github.com/EpicGamesExt/PixelStreamingInfrastructure/blob/master/Frontend/Docs/Customizing%20the%20Player%20Webpage.md

Error during npm run build:
```
Run npm audit for details.

ERROR in C:\Users\Administrator\Documents\Unreal Projects\MyProject2\Packaged Projects\Linux\MyProject2\Samples\PixelStreaming2\WebServers\Frontend\implementations\typescript\src\player.ts
./src/player.ts 30:45-66
[tsl] ERROR in C:\Users\Administrator\Documents\Unreal Projects\MyProject2\Packaged Projects\Linux\MyProject2\Samples\PixelStreaming2\WebServers\Frontend\implementations\typescript\src\player.ts(30,46)
      TS2304: Cannot find name 'UIElementCreationMode'.

ERROR in C:\Users\Administrator\Documents\Unreal Projects\MyProject2\Packaged Projects\Linux\MyProject2\Samples\PixelStreaming2\WebServers\Frontend\implementations\typescript\src\player.ts
./src/player.ts 35:43-64
[tsl] ERROR in C:\Users\Administrator\Documents\Unreal Projects\MyProject2\Packaged Projects\Linux\MyProject2\Samples\PixelStreaming2\WebServers\Frontend\implementations\typescript\src\player.ts(35,44)
      TS2304: Cannot find name 'UIElementCreationMode'.
```

## Question
Has there been a silly mistake from my end or has UE5.6 removed UIElementCreationMode? if yes, how do i resolve this issue?

**Comment by SavageCoder09** [comment]
Ok I have no idea why but the reran build with the same code, and its working now all on its own. Weird, but my issue is resolved.
